version: "3.9"

services:
  web:
    build: .
    container_name: babyshop
    working_dir: /app/babyshop_app
    ports:
      - "8025:8000"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - media:/app/babyshop_app/media
      - db:/app/babyshop_app/db
    command: >
      sh -c "
        cd babyshop_app &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "

volumes:
  media:
  static:
  db:
